<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metamodel" nsURI="platform:/resource/teachingassistant.metamodel/model/Metamodel.ecore"
    nsPrefix="teachingassistant.metamodel">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="TODO: Add documentation for metamodel. Hint: You may copy this element in the Ecore editor to add documentation to EClasses, EOperations, ..."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Department" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assistants" upperBound="-1"
        eType="#//Assistant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tutorials" upperBound="-1"
        eType="#//Tutorial" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeslots" upperBound="-1"
        eType="#//Timeslot" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lecturers" upperBound="-1"
        eType="#//Lecturer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="days" upperBound="-1" eType="#//Day"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assistant" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumHoursPerWeek" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumHoursPerWeek" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumDaysPerWeek" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="skills" upperBound="-1"
        eType="#//Skill" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tutorial" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SkillType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="givenBy" eType="#//Assistant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeslot" eType="#//Timeslot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lecturer" eType="#//Lecturer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Skill">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SkillType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SkillType">
    <eLiterals name="mathematics"/>
    <eLiterals name="electricalengineering" value="1"/>
    <eLiterals name="informatics" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Timeslot" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="day" eType="#//Day"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lecturer" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tutorials" upperBound="-1"
        eType="#//Tutorial"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SkillType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumNumberOfTas" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Day" eSuperTypes="#//NamedElement"/>
</ecore:EPackage>
