<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="LectureStudioModel" nsURI="platform:/resource/LectureStudioModel/model/LectureStudioModel.ecore"
    nsPrefix="LectureStudioModel">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="TODO: Add documentation for LectureStudioModel. Hint: You may copy this element in the Ecore editor to add documentation to EClasses, EOperations, ..."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="networks" upperBound="-1"
        eType="#//Network"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clock" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="time" eType="#//Time" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logs" upperBound="-1" eType="#//LogEntry"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lectureStudioServer" upperBound="-1"
        eType="#//LectureStudioServer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LectureStudioServer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lsNode" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="waitingClients" eType="#//WaitingClientQueue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientContainer" eType="#//ClientContainer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" eType="#//Data"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sendBandwidth" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiveBandwidth" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" eType="#//Data"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverConnection" lowerBound="1"
        eType="#//Connection" eOpposite="#//Connection/client"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientConnection" upperBound="-1"
        eType="#//Connection" eOpposite="#//Connection/server"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRelayClient" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clock" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transferredData" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depth" lowerBound="1" eType="#//NodeDepth"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/clientConnection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/serverConnection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transferRate" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transferredData" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaitingClientQueue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clients" upperBound="-1"
        eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clientId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bandwidth" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClientContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//Connection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionData" upperBound="-1"
        eType="#//ConnectionData" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeDepths" upperBound="-1"
        eType="#//NodeDepth" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Time">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="current" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clientId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeDepth">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
  </eClassifiers>
</ecore:EPackage>
