<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metamodel" nsURI="platform:/resource/teachingassistant.uni.metamodel/model/Metamodel.ecore"
    nsPrefix="teachingassistant.uni.metamodel">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaAllocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tas" upperBound="-1" eType="#//TeachingAssistant"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timetable" upperBound="-1"
        eType="#//TimeTableEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weeks" upperBound="-1"
        eType="#//Week" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="campuses" upperBound="-1"
        eType="#//Campus" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" upperBound="-1"
        eType="#//Room" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TeachingAssistant" eSuperTypes="#//NamedElement #//IdedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxHoursPerWeek" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxHoursTotal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unavailable" upperBound="-1"
        eType="#//TimeTableEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmploymentApproval">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rating" eType="#//EmploymentRating"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ta" lowerBound="1" eType="#//TeachingAssistant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ratingNumeric" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SessionOccurrence" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeTableWeek" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tas" lowerBound="1" upperBound="-1"
        eType="#//TeachingAssistant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousSolutionTas" upperBound="-1"
        eType="#//TeachingAssistant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//NamedElement #//IdedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="approvals" upperBound="-1"
        eType="#//EmploymentApproval" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sessions" upperBound="-1"
        eType="#//TeachingSession" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TeachingSession" eSuperTypes="#//NamedElement #//IdedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hoursPaidPerOccurrence"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numTasPerSession" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="occurrences" upperBound="-1"
        eType="#//SessionOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//TimeTableEntry" eOpposite="#//TimeTableEntry/session"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeTableWeeks" upperBound="-1"
        eType="#//Week"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeTableEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="session" lowerBound="1"
        eType="#//TeachingSession" eOpposite="#//TeachingSession/entries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeTableWeeks" upperBound="-1"
        eType="#//Week"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startMinutes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endMinutes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" eType="#//Room"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EmploymentRating">
    <eLiterals name="RED"/>
    <eLiterals name="AMBER" value="1"/>
    <eLiterals name="GREEN" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Week" eSuperTypes="#//IdedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Campus" eSuperTypes="#//IdedElement #//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Room" eSuperTypes="#//IdedElement #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="campus" eType="#//Campus"/>
  </eClassifiers>
</ecore:EPackage>
